# Generated by Django 4.0.5 on 2023-02-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_profile_addr_profile_codechef_profile_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.TextField(default='__'),
        ),
    ]
