# Generated by Django 3.2.10 on 2023-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.TextField(),
        ),
    ]
